//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectOperationServices.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class StudentTeacherDBEntities : DbContext
    {
        public StudentTeacherDBEntities()
            : base("name=StudentTeacherDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblstudent_details> tblstudent_details { get; set; }
        public virtual DbSet<tblstudent_payments> tblstudent_payments { get; set; }
        public virtual DbSet<tblstudent_registrations> tblstudent_registrations { get; set; }
        public virtual DbSet<tbltopic_contents> tbltopic_contents { get; set; }
        public virtual DbSet<tbltraining_course_fees> tbltraining_course_fees { get; set; }
        public virtual DbSet<tbltraining_courses> tbltraining_courses { get; set; }
        public virtual DbSet<tbltraining_topics> tbltraining_topics { get; set; }
    
        public virtual ObjectResult<sp_fetch_tblstudent_details_Result> sp_fetch_tblstudent_details(Nullable<int> student_id)
        {
            var student_idParameter = student_id.HasValue ?
                new ObjectParameter("student_id", student_id) :
                new ObjectParameter("student_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_fetch_tblstudent_details_Result>("sp_fetch_tblstudent_details", student_idParameter);
        }
    
        public virtual ObjectResult<sp_fetch_tblstudent_payments_Result> sp_fetch_tblstudent_payments(Nullable<int> payment_id)
        {
            var payment_idParameter = payment_id.HasValue ?
                new ObjectParameter("payment_id", payment_id) :
                new ObjectParameter("payment_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_fetch_tblstudent_payments_Result>("sp_fetch_tblstudent_payments", payment_idParameter);
        }
    
        public virtual ObjectResult<sp_fetch_tblstudent_registrations_Result> sp_fetch_tblstudent_registrations(Nullable<int> registration_id)
        {
            var registration_idParameter = registration_id.HasValue ?
                new ObjectParameter("registration_id", registration_id) :
                new ObjectParameter("registration_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_fetch_tblstudent_registrations_Result>("sp_fetch_tblstudent_registrations", registration_idParameter);
        }
    
        public virtual ObjectResult<sp_fetch_tbltopic_contents_Result> sp_fetch_tbltopic_contents(Nullable<int> content_id)
        {
            var content_idParameter = content_id.HasValue ?
                new ObjectParameter("content_id", content_id) :
                new ObjectParameter("content_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_fetch_tbltopic_contents_Result>("sp_fetch_tbltopic_contents", content_idParameter);
        }
    
        public virtual ObjectResult<sp_fetch_tbltraining_course_fees_Result> sp_fetch_tbltraining_course_fees(Nullable<int> fee_id)
        {
            var fee_idParameter = fee_id.HasValue ?
                new ObjectParameter("fee_id", fee_id) :
                new ObjectParameter("fee_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_fetch_tbltraining_course_fees_Result>("sp_fetch_tbltraining_course_fees", fee_idParameter);
        }
    
        public virtual ObjectResult<sp_fetch_tbltraining_courses_Result> sp_fetch_tbltraining_courses(Nullable<int> course_id)
        {
            var course_idParameter = course_id.HasValue ?
                new ObjectParameter("course_id", course_id) :
                new ObjectParameter("course_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_fetch_tbltraining_courses_Result>("sp_fetch_tbltraining_courses", course_idParameter);
        }
    
        public virtual ObjectResult<sp_fetch_tbltraining_topics_Result> sp_fetch_tbltraining_topics(Nullable<int> topic_id)
        {
            var topic_idParameter = topic_id.HasValue ?
                new ObjectParameter("topic_id", topic_id) :
                new ObjectParameter("topic_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_fetch_tbltraining_topics_Result>("sp_fetch_tbltraining_topics", topic_idParameter);
        }
    
        public virtual int sp_tblstudent_details(string type, Nullable<int> student_id, string student_name, string gender, string mobile_number, string email_address, string password, Nullable<System.DateTime> birth_date, string profile_photo, string qualification)
        {
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var student_idParameter = student_id.HasValue ?
                new ObjectParameter("student_id", student_id) :
                new ObjectParameter("student_id", typeof(int));
    
            var student_nameParameter = student_name != null ?
                new ObjectParameter("student_name", student_name) :
                new ObjectParameter("student_name", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("gender", gender) :
                new ObjectParameter("gender", typeof(string));
    
            var mobile_numberParameter = mobile_number != null ?
                new ObjectParameter("mobile_number", mobile_number) :
                new ObjectParameter("mobile_number", typeof(string));
    
            var email_addressParameter = email_address != null ?
                new ObjectParameter("email_address", email_address) :
                new ObjectParameter("email_address", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var birth_dateParameter = birth_date.HasValue ?
                new ObjectParameter("birth_date", birth_date) :
                new ObjectParameter("birth_date", typeof(System.DateTime));
    
            var profile_photoParameter = profile_photo != null ?
                new ObjectParameter("profile_photo", profile_photo) :
                new ObjectParameter("profile_photo", typeof(string));
    
            var qualificationParameter = qualification != null ?
                new ObjectParameter("qualification", qualification) :
                new ObjectParameter("qualification", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tblstudent_details", typeParameter, student_idParameter, student_nameParameter, genderParameter, mobile_numberParameter, email_addressParameter, passwordParameter, birth_dateParameter, profile_photoParameter, qualificationParameter);
        }
    
        public virtual int sp_tblstudent_payments(string type, Nullable<int> payment_id, Nullable<int> registration_id, Nullable<System.DateTime> payment_date, Nullable<double> payment_amount, string payment_mode, string payment_description)
        {
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var payment_idParameter = payment_id.HasValue ?
                new ObjectParameter("payment_id", payment_id) :
                new ObjectParameter("payment_id", typeof(int));
    
            var registration_idParameter = registration_id.HasValue ?
                new ObjectParameter("registration_id", registration_id) :
                new ObjectParameter("registration_id", typeof(int));
    
            var payment_dateParameter = payment_date.HasValue ?
                new ObjectParameter("payment_date", payment_date) :
                new ObjectParameter("payment_date", typeof(System.DateTime));
    
            var payment_amountParameter = payment_amount.HasValue ?
                new ObjectParameter("payment_amount", payment_amount) :
                new ObjectParameter("payment_amount", typeof(double));
    
            var payment_modeParameter = payment_mode != null ?
                new ObjectParameter("payment_mode", payment_mode) :
                new ObjectParameter("payment_mode", typeof(string));
    
            var payment_descriptionParameter = payment_description != null ?
                new ObjectParameter("payment_description", payment_description) :
                new ObjectParameter("payment_description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tblstudent_payments", typeParameter, payment_idParameter, registration_idParameter, payment_dateParameter, payment_amountParameter, payment_modeParameter, payment_descriptionParameter);
        }
    
        public virtual int sp_tblstudent_registrations(string type, Nullable<int> registration_id, Nullable<int> student_id, Nullable<int> course_id, Nullable<System.DateTime> registration_date, Nullable<double> discount)
        {
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var registration_idParameter = registration_id.HasValue ?
                new ObjectParameter("registration_id", registration_id) :
                new ObjectParameter("registration_id", typeof(int));
    
            var student_idParameter = student_id.HasValue ?
                new ObjectParameter("student_id", student_id) :
                new ObjectParameter("student_id", typeof(int));
    
            var course_idParameter = course_id.HasValue ?
                new ObjectParameter("course_id", course_id) :
                new ObjectParameter("course_id", typeof(int));
    
            var registration_dateParameter = registration_date.HasValue ?
                new ObjectParameter("registration_date", registration_date) :
                new ObjectParameter("registration_date", typeof(System.DateTime));
    
            var discountParameter = discount.HasValue ?
                new ObjectParameter("discount", discount) :
                new ObjectParameter("discount", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tblstudent_registrations", typeParameter, registration_idParameter, student_idParameter, course_idParameter, registration_dateParameter, discountParameter);
        }
    
        public virtual int sp_tbltopic_contents(string type, Nullable<int> content_id, Nullable<int> topic_id, string content_name)
        {
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var content_idParameter = content_id.HasValue ?
                new ObjectParameter("content_id", content_id) :
                new ObjectParameter("content_id", typeof(int));
    
            var topic_idParameter = topic_id.HasValue ?
                new ObjectParameter("topic_id", topic_id) :
                new ObjectParameter("topic_id", typeof(int));
    
            var content_nameParameter = content_name != null ?
                new ObjectParameter("content_name", content_name) :
                new ObjectParameter("content_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tbltopic_contents", typeParameter, content_idParameter, topic_idParameter, content_nameParameter);
        }
    
        public virtual int sp_tbltraining_course_fees(string type, Nullable<int> fee_id, Nullable<int> course_id, Nullable<double> fees_amount, Nullable<double> gst, string fee_mode)
        {
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var fee_idParameter = fee_id.HasValue ?
                new ObjectParameter("fee_id", fee_id) :
                new ObjectParameter("fee_id", typeof(int));
    
            var course_idParameter = course_id.HasValue ?
                new ObjectParameter("course_id", course_id) :
                new ObjectParameter("course_id", typeof(int));
    
            var fees_amountParameter = fees_amount.HasValue ?
                new ObjectParameter("fees_amount", fees_amount) :
                new ObjectParameter("fees_amount", typeof(double));
    
            var gstParameter = gst.HasValue ?
                new ObjectParameter("gst", gst) :
                new ObjectParameter("gst", typeof(double));
    
            var fee_modeParameter = fee_mode != null ?
                new ObjectParameter("fee_mode", fee_mode) :
                new ObjectParameter("fee_mode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tbltraining_course_fees", typeParameter, fee_idParameter, course_idParameter, fees_amountParameter, gstParameter, fee_modeParameter);
        }
    
        public virtual int sp_tbltraining_courses(string type, Nullable<int> course_id, string course_name)
        {
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var course_idParameter = course_id.HasValue ?
                new ObjectParameter("course_id", course_id) :
                new ObjectParameter("course_id", typeof(int));
    
            var course_nameParameter = course_name != null ?
                new ObjectParameter("course_name", course_name) :
                new ObjectParameter("course_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tbltraining_courses", typeParameter, course_idParameter, course_nameParameter);
        }
    
        public virtual int sp_tbltraining_topics(string type, Nullable<int> topic_id, string topic_name)
        {
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var topic_idParameter = topic_id.HasValue ?
                new ObjectParameter("topic_id", topic_id) :
                new ObjectParameter("topic_id", typeof(int));
    
            var topic_nameParameter = topic_name != null ?
                new ObjectParameter("topic_name", topic_name) :
                new ObjectParameter("topic_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tbltraining_topics", typeParameter, topic_idParameter, topic_nameParameter);
        }
    }
}
